// src/App.tsx
import React, { useState } from "react";
import axios from "axios";

interface StatsProps {
  average: number;
  isDiagonal: boolean;
  max: number;
  min: number;
  sum: number;
}

const App: React.FC = () => {
  const [matrixSize, setMatrixSize] = useState<number>(3);
  const [matrixInput, setMatrixInput] = useState<number[][]>([]);
  const [matrixRotate, setMatrixRotate] = useState<number[][] | null>(null);
  const [qMatrix, setQMatrix] = useState<number[][] | null>(null);
  const [rMatrix, setRMatrix] = useState<number[][] | null>(null);
  const [statsQ, setStatsQ] = useState<StatsProps | null>(null);
  const [statsR, setStatsR] = useState<StatsProps | null>(null);
  const [loading, setLoading] = useState<boolean>(false);

  const createEmptyMatrix = (size: number): number[][] => {
    const matrix = [];
    for (let i = 0; i < size; i++) {
      const row = Array(size).fill(0);
      matrix.push(row);
    }
    return matrix;
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>, row: number, col: number) => {
    const value = Number(e.target.value);
    const newMatrix = [...matrixInput];
    newMatrix[row][col] = value;
    setMatrixInput(newMatrix);
  };

  const sendMatrix = async () => {
    setLoading(true);
    try {
      const response = await axios.post(`${import.meta.env.VITE_PORT_GO}/qr`, matrixInput);
      console.log("Respuesta del servidor:", response.data);

      const data = response.data;
      setMatrixRotate(data.RotatedMatrix);
      setQMatrix(data.QMatrix);
      setRMatrix(data.RMatrix);
      setStatsQ(data.QStats);
      setStatsR(data.RStats);
    } catch (error) {
      console.error("Error al procesar la matriz:", error);
    } finally {
      setLoading(false);
    }
  };

  const formatMatrix = (matrix: number[][], readonly: boolean) => {
    return (
      <table style={tableStyle}>
        <tbody>
          {matrix.map((row, rowIndex) => (
            <tr key={rowIndex}>
              {row.map((value, colIndex) => (
                <td key={colIndex}>
                  <input
                    type="number"
                    value={value}
                    onChange={(e) => handleInputChange(e, rowIndex, colIndex)}
                    style={inputStyle}
                    readOnly={readonly}  
                  />
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    );
  };

  const formatStats = (stats: StatsProps) => {
    // console.log(stats.isDiagonal)
    return (
      <table style={tableStyle}>
        <tbody>
          <tr>
            <td><strong>Promedio:</strong></td>
            <td>{stats.average.toFixed(4)}</td>
          </tr>
          <tr>
            <td><strong>¿Es diagonal?:</strong></td>
            <td>{stats.isDiagonal ? "Sí" : "No"}</td>
          </tr>
          <tr>
            <td><strong>Máximo:</strong></td>
            <td>{stats.max.toFixed(4)}</td>
          </tr>
          <tr>
            <td><strong>Mínimo:</strong></td>
            <td>{stats.min.toFixed(4)}</td>
          </tr>
          <tr>
            <td><strong>Suma:</strong></td>
            <td>{stats.sum.toFixed(4)}</td>
          </tr>
        </tbody>
      </table>
    );
  };

  const handleSizeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newSize = parseInt(e.target.value);
    setMatrixSize(newSize);
    setMatrixInput(createEmptyMatrix(newSize));
  };

  return (
    <div style={containerStyle}>
      <h1 style={headingStyle}>Factorización QR y Estadísticas de Matriz</h1>

      <div style={inputGroupStyle}>
        <label htmlFor="matrixSize" style={labelStyle}>Tamaño de la matriz (N x N):</label>
        <input
          id="matrixSize"
          type="number"
          min="2"
          value={matrixSize}
          onChange={handleSizeChange}
          style={inputStyle}
        />
      </div>

      <div>
        <h3 style={sectionHeadingStyle}>Ingresa la matriz:</h3>
        {formatMatrix(matrixInput, false)}
        <br />
        <button onClick={sendMatrix} disabled={loading} style={buttonStyle}>
          {loading ? "Cargando..." : "Enviar Matriz"}
        </button>
      </div>

      {loading && <p style={loadingTextStyle}>Cargando resultados...</p>}

      {matrixRotate && (
        <div style={matrixContainerStyle}>
          <h3 style={sectionHeadingStyle}>Matriz Rotada</h3>
          {formatMatrix(matrixRotate, true)}
        </div>
      )}

      {qMatrix && (
        <div style={matrixContainerStyle}>
          <h3 style={sectionHeadingStyle}>Matriz Q</h3>
          {formatMatrix(qMatrix, true)}
          <h3 style={sectionHeadingStyle}>Estadísticas de Q</h3>
          {statsQ && formatStats(statsQ)}
        </div>
      )}

      {rMatrix && (
        <div style={matrixContainerStyle}>
          <h3 style={sectionHeadingStyle}>Matriz R</h3>
          {formatMatrix(rMatrix, true)}
          <h3 style={sectionHeadingStyle}>Estadísticas de R</h3>
          {statsR && formatStats(statsR)}
        </div>
      )}
    </div>
  );
};

const containerStyle: React.CSSProperties = {
  fontFamily: "Arial, sans-serif",
  padding: "30px",
  backgroundColor: "#181818",  // Fondo oscuro
  color: "#eaeaea",  // Texto claro
  borderRadius: "8px",
  maxWidth: "900px",
  margin: "0 auto",
  display: "block",  // Asegura que el contenedor sea un bloque y se centre
};

const headingStyle: React.CSSProperties = {
  textAlign: "center",
  color: "#eaeaea",  // Texto claro
};

const inputGroupStyle: React.CSSProperties = {
  marginBottom: "20px",
};

const labelStyle: React.CSSProperties = {
  fontSize: "16px",
  marginBottom: "8px",
  display: "block",
  color: "#ccc",  // Color más suave para las etiquetas
};

const inputStyle: React.CSSProperties = {
  width: "100%",
  padding: "10px",
  fontSize: "16px",
  borderRadius: "8px",
  border: "1px solid #555",  // Bordes más oscuros
  marginBottom: "20px",
  boxSizing: "border-box",
  backgroundColor: "#333",  // Fondo oscuro para inputs
  color: "#eaeaea",  // Texto claro en inputs
};

const buttonStyle: React.CSSProperties = {
  backgroundColor: "#4CAF50",  // Verde brillante
  color: "white",
  border: "none",
  padding: "12px 24px",
  fontSize: "16px",
  borderRadius: "8px",
  cursor: "pointer",
  width: "100%",
  transition: "background-color 0.3s",
};

const loadingTextStyle: React.CSSProperties = {
  textAlign: "center",
  fontSize: "18px",
  color: "#bbb",  // Gris claro para el texto de carga
};

const sectionHeadingStyle: React.CSSProperties = {
  color: "#eaeaea",  // Texto claro para encabezados de secciones
  marginBottom: "10px",
};

const matrixContainerStyle: React.CSSProperties = {
  marginBottom: "40px",
};

const tableStyle: React.CSSProperties = {
  width: "100%",
  borderCollapse: "collapse",
  marginBottom: "20px",
  color: "#eaeaea",  // Texto de la tabla claro
  backgroundColor: "#222",  // Fondo oscuro para la tabla
};



export default App;

// src/App.vue
<template>
  <div class="container">
    <h1 class="heading">Factorización QR y Estadísticas de Matriz</h1>

    <ErrorMessage v-if="error" :message="error" @close="closeError" />

    <div class="input-group">
      <label for="matrixSize" class="label">
        Tamaño de la matriz (N x N):
      </label>
      <input id="matrixSize" v-model.number="matrixSize" type="number" min="2" max="10" class="size-input"
        @change="handleSizeChange" />
    </div>

    <div>
      <h3 class="section-heading">Ingresa la matriz:</h3>
      <MatrixInput :matrix="matrixInput" :readonly="false" @update:matrix="handleMatrixUpdate" />
      <br />
      <button :disabled="loading" :class="['button', { 'button-disabled': loading }]" @click="sendMatrix">
        {{ loading ? 'Cargando...' : 'Enviar Matriz' }}
      </button>
    </div>

    <p v-if="loading" class="loading-text">Cargando resultados...</p>

    <template v-if="matrixResponse">
      <div class="matrix-container">
        <h3 class="section-heading">Matriz Rotada</h3>
        <MatrixInput :matrix="matrixResponse.RotatedMatrix" :readonly="true" />
      </div>

      <div class="matrix-container">
        <h3 class="section-heading">Matriz Q</h3>
        <MatrixInput :matrix="matrixResponse.QMatrix" :readonly="true" />
        <h3 class="section-heading">Estadísticas de Q</h3>
        <MatrixStats :stats="matrixResponse.QStats" />
      </div>

      <div class="matrix-container">
        <h3 class="section-heading">Matriz R</h3>
        <MatrixInput :matrix="matrixResponse.RMatrix" :readonly="true" />
        <h3 class="section-heading">Estadísticas de R</h3>
        <MatrixStats :stats="matrixResponse.RStats" />
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import MatrixInput from './components/MatrixInput.vue';
import MatrixStats from './components/MatrixStats.vue';
import ErrorMessage from './components/ErrorMessage.vue';
import { MatrixService } from './services/matrix.service';
import { MatrixResponseEntity } from './entities/matrix-response.entity';
import { createEmptyMatrix } from './mappers/matrix.mapper';
import { logger } from './utils/logger';
import { isValidMatrixSize } from './utils/validators';

const matrixSize = ref<number>(3);
const matrixInput = ref<number[][]>([]);
const matrixResponse = ref<MatrixResponseEntity | null>(null);
const loading = ref<boolean>(false);
const error = ref<string | null>(null);
const matrixService = new MatrixService();

onMounted(() => {
  matrixInput.value = createEmptyMatrix(matrixSize.value);
  logger.info('Aplicación inicializada', { matrixSize: matrixSize.value });
});

const handleMatrixUpdate = (newMatrix: number[][]): void => {
  matrixInput.value = newMatrix;
  logger.debug('Matriz actualizada');
};

const handleSizeChange = (): void => {
  if (!isValidMatrixSize(matrixSize.value)) {
    logger.warn('Tamaño de matriz inválido', { size: matrixSize.value });
    error.value = 'El tamaño debe estar entre 2 y 10';
    return;
  }

  matrixInput.value = createEmptyMatrix(matrixSize.value);
  matrixResponse.value = null;
  error.value = null;
  logger.info('Tamaño de matriz cambiado', { newSize: matrixSize.value });
};

const sendMatrix = async (): Promise<void> => {
  loading.value = true;
  error.value = null;
  logger.info('Enviando matriz para análisis');

  try {
    const response = await matrixService.analyzeMatrix(matrixInput.value);
    matrixResponse.value = response;
    logger.info('Análisis recibido exitosamente');
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : 'Error desconocido';
    error.value = errorMessage;
    logger.error('Error al analizar matriz', { error: errorMessage });
  } finally {
    loading.value = false;
  }
};

const closeError = (): void => {
  error.value = null;
};
</script>

<style scoped>
.container {
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  padding: 30px;
  background-color: #181818;
  color: #eaeaea;
  border-radius: 8px;
  max-width: 900px;
  margin: 0 auto;
}

.heading {
  text-align: center;
  color: #eaeaea;
  margin-bottom: 30px;
}

.input-group {
  margin-bottom: 20px;
}

.label {
  font-size: 16px;
  margin-bottom: 8px;
  display: block;
  color: #ccc;
}

.size-input {
  width: 100%;
  padding: 10px;
  font-size: 16px;
  border-radius: 8px;
  border: 1px solid #555;
  margin-bottom: 20px;
  box-sizing: border-box;
  background-color: #333;
  color: #eaeaea;
}

.button {
  background-color: #4caf50;
  color: white;
  border: none;
  padding: 12px 24px;
  font-size: 16px;
  border-radius: 8px;
  cursor: pointer;
  width: 100%;
  transition: background-color 0.3s;
}

.button:hover:not(.button-disabled) {
  background-color: #45a049;
}

.button-disabled {
  background-color: #6c757d;
  cursor: not-allowed;
}

.loading-text {
  text-align: center;
  font-size: 18px;
  color: #bbb;
  margin: 20px 0;
}

.section-heading {
  color: #eaeaea;
  margin-bottom: 10px;
  margin-top: 20px;
}

.matrix-container {
  margin-bottom: 40px;
}
</style>
